"""
Environmental Data Layer for Oil-Spill Drift Module.

Provides abstractions and implementations for retrieving wind and ocean-current
time-series observations.

Architecture & Providers:
- EnvironmentalDataProvider (ABC): Abstract base contract for all environmental providers.
- SyntheticEnvironmentalProvider: Deterministic synthetic data provider for prototyping/testing.
- FileEnvironmentalProvider: File/memory-based provider loading CSV or JSON time-series data.
- RealEnvironmentalProvider: Placeholder adapter for future live external API feeds
  (e.g., Copernicus Marine Service, NOAA, OpenWeather).

Documentation Notes:
- Synthetic data generated by SyntheticEnvironmentalProvider is DEMO data for testing.
- File-based data loaded by FileEnvironmentalProvider represents externally supplied measurements.
- All timestamps MUST be timezone-aware (UTC preferred). Timezone-naive timestamps are rejected.
- Observations are returned in chronological order with inclusive start/end times.
- Nearest-timestamp selection is used for observation lookups; NO interpolation is performed.
- Maximum time-gap behavior raises an EnvironmentalDataUnavailableError if the gap exceeds threshold.
- No live external network calls are performed in this phase.
"""

from abc import ABC, abstractmethod
import csv
from datetime import datetime, timedelta, timezone
import json
import math
from pathlib import Path
from typing import List, Optional, Union, Dict, Any

from .geo_utils import validate_coordinates
from .models import EnvironmentalObservation


class EnvironmentalDataUnavailableError(Exception):
    """Raised when requested environmental data is unavailable or exceeds max gap."""
    pass


class EnvironmentalDataProvider(ABC):
    """
    Abstract base class for environmental data providers.
    
    Subclasses can implement fetching from synthetic generators, CSV/JSON files,
    in-memory datasets, or future live oceanographic services.
    """

    @abstractmethod
    def get_observations(
        self,
        start_time: datetime,
        end_time: datetime,
        latitude: float,
        longitude: float,
        interval_minutes: float = 30.0,
    ) -> List[EnvironmentalObservation]:
        """
        Retrieve a time-series of environmental observations for a specific location.

        :param start_time: Inclusive start timestamp (timezone-aware)
        :param end_time: Inclusive end timestamp (timezone-aware)
        :param latitude: Latitude in degrees (-90 to 90)
        :param longitude: Longitude in degrees (-180 to 180)
        :param interval_minutes: Time step interval in minutes (default: 30.0)
        :return: Chronological list of EnvironmentalObservation instances
        """
        pass


class SyntheticEnvironmentalProvider(EnvironmentalDataProvider):
    """
    Deterministic synthetic environmental data provider for testing and development.
    
    Generates reproducible wind and ocean current time-series without external network dependencies.
    Data source identifier is always 'synthetic_demo'.
    
    This is DEMO data only and must NOT be treated as real meteorological observations.
    """

    SOURCE_NAME: str = "synthetic_demo"

    def get_observations(
        self,
        start_time: datetime,
        end_time: datetime,
        latitude: float,
        longitude: float,
        interval_minutes: float = 30.0,
    ) -> List[EnvironmentalObservation]:
        """
        Generates deterministic synthetic environmental observations.

        :param start_time: Inclusive start datetime (timezone-aware)
        :param end_time: Inclusive end datetime (timezone-aware)
        :param latitude: Target latitude in degrees [-90, 90]
        :param longitude: Target longitude in degrees [-180, 180]
        :param interval_minutes: Time step interval in minutes (> 0)
        :return: Chronological list of EnvironmentalObservation instances
        :raises ValueError: If timestamps are naive, interval <= 0, start_time > end_time, or coords invalid.
        """
        validate_coordinates(latitude, longitude)

        if start_time is None or start_time.tzinfo is None or start_time.tzinfo.utcoffset(start_time) is None:
            raise ValueError("start_time must be timezone-aware.")
        if end_time is None or end_time.tzinfo is None or end_time.tzinfo.utcoffset(end_time) is None:
            raise ValueError("end_time must be timezone-aware.")

        if start_time > end_time:
            raise ValueError(f"start_time ({start_time}) cannot be after end_time ({end_time}).")

        if interval_minutes is None or isinstance(interval_minutes, bool) or not isinstance(interval_minutes, (int, float)):
            raise ValueError("interval_minutes must be a positive number.")
        if interval_minutes <= 0:
            raise ValueError(f"interval_minutes must be > 0, got {interval_minutes}")

        observations: List[EnvironmentalObservation] = []
        current_time = start_time
        delta = timedelta(minutes=float(interval_minutes))

        while current_time <= end_time:
            elapsed_hours = (current_time - start_time).total_seconds() / 3600.0

            wind_speed = round(7.5 + 2.0 * math.sin(elapsed_hours * math.pi / 12.0) + 0.1 * (latitude % 5), 2)
            wind_speed = max(0.0, wind_speed)

            wind_dir = round((135.0 + elapsed_hours * 5.0 + abs(longitude) % 30) % 360.0, 2)

            current_speed = round(0.35 + 0.1 * math.cos(elapsed_hours * math.pi / 6.0), 2)
            current_speed = max(0.0, current_speed)

            current_dir = round((210.0 + elapsed_hours * 2.0) % 360.0, 2)

            obs = EnvironmentalObservation(
                timestamp=current_time,
                latitude=float(latitude),
                longitude=float(longitude),
                wind_speed_mps=wind_speed,
                wind_direction_deg=wind_dir,
                current_speed_mps=current_speed,
                current_direction_deg=current_dir,
            )
            observations.append(obs)
            current_time += delta

        return observations


class FileEnvironmentalProvider(EnvironmentalDataProvider):
    """
    Environmental data provider that loads observations from CSV, JSON files,
    or in-memory records.
    """

    REQUIRED_FIELDS = {
        "timestamp",
        "latitude",
        "longitude",
        "wind_speed_mps",
        "wind_direction_deg",
        "current_speed_mps",
        "current_direction_deg",
    }

    def __init__(
        self,
        data_source: Union[str, Path, List[Dict[str, Any]]],
        format: str = "auto",
    ):
        """
        Initialize the file/memory-based environmental data provider.

        :param data_source: Path to CSV/JSON file, raw CSV/JSON string, or list of dict records.
        :param format: Data format ('csv', 'json', or 'auto').
        :raises ValueError: If data is invalid, unparseable, or missing required fields.
        """
        self.observations: List[EnvironmentalObservation] = []
        self._load_and_validate(data_source, format)

    def _parse_timestamp(self, ts_raw: Any) -> datetime:
        """Parses and validates that timestamp is UTC/timezone-aware."""
        if isinstance(ts_raw, datetime):
            if ts_raw.tzinfo is None or ts_raw.tzinfo.utcoffset(ts_raw) is None:
                raise ValueError(f"Timestamp must be timezone-aware, got naive datetime: {ts_raw}")
            return ts_raw.astimezone(timezone.utc)

        if not isinstance(ts_raw, str) or not ts_raw.strip():
            raise ValueError(f"Invalid timestamp value: {ts_raw}")

        ts_str = ts_raw.strip()
        # Check for naive ISO string without offset or Z
        if "Z" not in ts_str.upper() and "+" not in ts_str and "-" not in ts_str[10:]:
            raise ValueError(f"Timestamp string must include timezone offset or Z: {ts_raw}")

        try:
            dt = datetime.fromisoformat(ts_str.replace("Z", "+00:00").replace("z", "+00:00"))
            if dt.tzinfo is None or dt.tzinfo.utcoffset(dt) is None:
                raise ValueError(f"Parsed datetime is naive: {ts_raw}")
            return dt.astimezone(timezone.utc)
        except Exception as e:
            raise ValueError(f"Failed to parse timezone-aware ISO timestamp '{ts_raw}': {str(e)}") from e

    def _validate_record(self, record: Dict[str, Any]) -> EnvironmentalObservation:
        """Validates a dictionary record and constructs an EnvironmentalObservation."""
        missing = self.REQUIRED_FIELDS - set(record.keys())
        if missing:
            raise ValueError(f"Missing required environmental data fields: {sorted(list(missing))}")

        ts = self._parse_timestamp(record["timestamp"])
        
        try:
            lat = float(record["latitude"])
            lon = float(record["longitude"])
            validate_coordinates(lat, lon)
        except Exception as e:
            raise ValueError(f"Invalid coordinates in environmental record ({record.get('latitude')}, {record.get('longitude')}): {str(e)}") from e

        try:
            wind_speed = float(record["wind_speed_mps"])
            if wind_speed < 0:
                raise ValueError(f"wind_speed_mps cannot be negative, got {wind_speed}")
        except Exception as e:
            raise ValueError(f"Invalid wind_speed_mps value '{record.get('wind_speed_mps')}': {str(e)}") from e

        try:
            wind_dir = float(record["wind_direction_deg"]) % 360.0
            if wind_dir < 0:
                wind_dir += 360.0
        except Exception as e:
            raise ValueError(f"Invalid wind_direction_deg value '{record.get('wind_direction_deg')}': {str(e)}") from e

        try:
            current_speed = float(record["current_speed_mps"])
            if current_speed < 0:
                raise ValueError(f"current_speed_mps cannot be negative, got {current_speed}")
        except Exception as e:
            raise ValueError(f"Invalid current_speed_mps value '{record.get('current_speed_mps')}': {str(e)}") from e

        try:
            current_dir = float(record["current_direction_deg"]) % 360.0
            if current_dir < 0:
                current_dir += 360.0
        except Exception as e:
            raise ValueError(f"Invalid current_direction_deg value '{record.get('current_direction_deg')}': {str(e)}") from e

        return EnvironmentalObservation(
            timestamp=ts,
            latitude=lat,
            longitude=lon,
            wind_speed_mps=wind_speed,
            wind_direction_deg=wind_dir,
            current_speed_mps=current_speed,
            current_direction_deg=current_dir,
        )

    def _load_and_validate(self, data_source: Union[str, Path, List[Dict[str, Any]]], format: str) -> None:
        """Loads records from file path, raw string, or list of dicts."""
        records: List[Dict[str, Any]] = []

        if isinstance(data_source, list):
            records = data_source
        elif isinstance(data_source, (str, Path)):
            path_or_str = str(data_source)
            p = Path(path_or_str)

            if p.exists() and p.is_file():
                content = p.read_text(encoding="utf-8")
                fmt = format.lower()
                if fmt == "auto":
                    fmt = "json" if p.suffix.lower() == ".json" else "csv"
            else:
                content = path_or_str
                fmt = format.lower()
                if fmt == "auto":
                    fmt = "json" if content.strip().startswith(("[", "{")) else "csv"

            if fmt == "json":
                try:
                    loaded = json.loads(content)
                    records = loaded if isinstance(loaded, list) else [loaded]
                except Exception as e:
                    raise ValueError(f"Failed to parse JSON environmental data: {str(e)}") from e
            else:
                # CSV format parsing
                try:
                    lines = [line for line in content.splitlines() if line.strip() and not line.strip().startswith("#")]
                    reader = csv.DictReader(lines)
                    records = [dict(row) for row in reader]
                    if not records:
                        raise ValueError("CSV environmental data is empty or missing headers.")
                except Exception as e:
                    raise ValueError(f"Failed to parse CSV environmental data: {str(e)}") from e

        parsed_obs: List[EnvironmentalObservation] = []
        for rec in records:
            obs = self._validate_record(rec)
            parsed_obs.append(obs)

        # Sort chronologically by timestamp
        parsed_obs.sort(key=lambda o: o.timestamp)
        self.observations = parsed_obs

    def get_observations(
        self,
        start_time: datetime,
        end_time: datetime,
        latitude: float,
        longitude: float,
        interval_minutes: float = 30.0,
    ) -> List[EnvironmentalObservation]:
        """
        Retrieves matching environmental observations within the requested time window.

        :param start_time: Inclusive start timestamp (timezone-aware)
        :param end_time: Inclusive end timestamp (timezone-aware)
        :param latitude: Target latitude (used for validation)
        :param longitude: Target longitude (used for validation)
        :param interval_minutes: Interval setting (ignored for fixed file records)
        :return: Chronological list of EnvironmentalObservation instances
        :raises ValueError: If input timestamps or coordinates are invalid
        """
        validate_coordinates(latitude, longitude)

        if start_time is None or start_time.tzinfo is None or start_time.tzinfo.utcoffset(start_time) is None:
            raise ValueError("start_time must be timezone-aware.")
        if end_time is None or end_time.tzinfo is None or end_time.tzinfo.utcoffset(end_time) is None:
            raise ValueError("end_time must be timezone-aware.")

        if start_time > end_time:
            raise ValueError(f"start_time ({start_time}) cannot be after end_time ({end_time}).")

        st_utc = start_time.astimezone(timezone.utc)
        et_utc = end_time.astimezone(timezone.utc)

        filtered = [obs for obs in self.observations if st_utc <= obs.timestamp <= et_utc]
        return filtered


class RealEnvironmentalProvider(EnvironmentalDataProvider):
    """
    Placeholder adapter for future live external API feeds (e.g., Copernicus Marine Service,
    NOAA GFS, OpenWeather Marine API).
    
    Live network API integration is not active in this phase.
    """

    def __init__(self, api_key: Optional[str] = None, base_url: Optional[str] = None):
        self.api_key = api_key
        self.base_url = base_url

    def get_observations(
        self,
        start_time: datetime,
        end_time: datetime,
        latitude: float,
        longitude: float,
        interval_minutes: float = 30.0,
    ) -> List[EnvironmentalObservation]:
        """
        Placeholder method for fetching real-time environmental data.

        :raises NotImplementedError: Always raised in prototype phase to prevent accidental external network calls.
        """
        raise NotImplementedError(
            "RealEnvironmentalProvider is a placeholder adapter for future live API integration. "
            "Use FileEnvironmentalProvider or SyntheticEnvironmentalProvider."
        )


def get_nearest_observation(
    observations: List[EnvironmentalObservation],
    target_time: datetime,
    max_gap_minutes: Optional[float] = None,
) -> EnvironmentalObservation:
    """
    Selects the closest EnvironmentalObservation to a requested target timestamp.

    No interpolation is performed. If no observations exist, or if the time difference
    to the nearest observation exceeds max_gap_minutes, raises EnvironmentalDataUnavailableError.

    :param observations: List of EnvironmentalObservation instances
    :param target_time: Target datetime (must be timezone-aware)
    :param max_gap_minutes: Maximum allowable time difference in minutes (optional)
    :return: Closest EnvironmentalObservation instance
    :raises ValueError: If target_time is timezone-naive
    :raises EnvironmentalDataUnavailableError: If observations list is empty or closest gap exceeds max_gap_minutes
    """
    if target_time is None or target_time.tzinfo is None or target_time.tzinfo.utcoffset(target_time) is None:
        raise ValueError("target_time must be timezone-aware.")

    if not observations:
        raise EnvironmentalDataUnavailableError("No environmental observations provided.")

    if max_gap_minutes is not None:
        if isinstance(max_gap_minutes, bool) or not isinstance(max_gap_minutes, (int, float)):
            raise ValueError("max_gap_minutes must be a numeric value.")
        if max_gap_minutes < 0:
            raise ValueError("max_gap_minutes cannot be negative.")

    target_utc = target_time.astimezone(timezone.utc)
    best_obs: Optional[EnvironmentalObservation] = None
    min_diff_seconds: float = float("inf")

    for obs in observations:
        diff_seconds = abs((obs.timestamp - target_utc).total_seconds())
        if diff_seconds < min_diff_seconds:
            min_diff_seconds = diff_seconds
            best_obs = obs

    if best_obs is None:
        raise EnvironmentalDataUnavailableError("Could not find any suitable environmental observation.")

    min_diff_minutes = min_diff_seconds / 60.0

    if max_gap_minutes is not None and min_diff_minutes > float(max_gap_minutes):
        raise EnvironmentalDataUnavailableError(
            f"Closest environmental observation is {min_diff_minutes:.1f} minutes away from target time, "
            f"which exceeds the maximum allowed gap of {max_gap_minutes:.1f} minutes."
        )

    return best_obs
